# Generated by Django 5.2.1 on 2025-05-20 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('ENGINE', 'Engine'), ('TRANSMISSION', 'Transmission'), ('GASKET', 'Gaskets, and Sealing'), ('DRIVE', 'Drive System'), ('SUSPENSION', 'Suspension, Damping, and Steering'), ('BRAKE', 'Brakes'), ('ELECTRIC', 'Electrics, and Electronics'), ('EXHAUST', 'Exhaust Systems'), ('BODY', 'Body, and Exterior'), ('INTERIOR', 'Interior, and Comfort'), ('MISC', 'Fasteners, and Miscellaneous'), ('TYRES', 'Tyres and related products')], max_length=12)),
                ('source', models.URLField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('amount', models.IntegerField()),
                ('completion', models.BooleanField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CART.part')),
            ],
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('amount', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CART.part')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CART.modification')),
                ('required', models.ManyToManyField(related_name='requirements', to='CART.modification')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=8, unique=True)),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('nickname', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('completion', models.BooleanField()),
                ('modifications', models.ManyToManyField(related_name='stages', to='CART.modification')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CART.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('MAINTAIN', 'Maintenance, and Service'), ('REPAIR', 'Repairs')], max_length=8)),
                ('completion', models.BooleanField()),
                ('fixes', models.ManyToManyField(related_name='repairs', to='CART.fix')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CART.vehicle')),
            ],
        ),
    ]
